# Generated by Django 3.2.9 on 2022-09-25 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('experience_year', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(upload_to='master/avatar/')),
                ('phone_number', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=128)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master', to='master.district')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='SubSpeciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub', to='master.speciality')),
            ],
        ),
        migrations.CreateModel(
            name='MasterSubSpeciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(default='Kelishiladi', max_length=128)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_speciality', to='master.master')),
                ('sub_speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_speciality', to='master.subspeciality')),
            ],
        ),
        migrations.AddField(
            model_name='master',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master', to='master.region'),
        ),
        migrations.AddField(
            model_name='master',
            name='specialities',
            field=models.ManyToManyField(related_name='master', to='master.Speciality'),
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district', to='master.region'),
        ),
    ]
