# Generated by Django 3.2.9 on 2022-09-30 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_alter_master_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='address',
            field=models.CharField(default=' ', max_length=128),
        ),
        migrations.AlterField(
            model_name='master',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='master', to='master.district'),
        ),
        migrations.AlterField(
            model_name='master',
            name='image',
            field=models.ImageField(null=True, upload_to='master/avatar/'),
        ),
        migrations.AlterField(
            model_name='master',
            name='name',
            field=models.CharField(default=' ', max_length=64),
        ),
        migrations.AlterField(
            model_name='master',
            name='phone_number',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='master',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='master', to='master.region'),
        ),
        migrations.AlterField(
            model_name='master',
            name='specialities',
            field=models.ManyToManyField(null=True, related_name='master', to='master.Speciality'),
        ),
    ]
