# Generated by Django 3.2.9 on 2022-09-30 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rm_unused_fields'),
        ('master', '0003_auto_20220930_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='master', to='users.user'),
            preserve_default=False,
        ),
    ]
