# Generated by Django 3.2.9 on 2022-10-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_auto_20221012_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='image',
            field=models.ImageField(null=True, upload_to='master/avatar/'),
        ),
    ]
