# Generated by Django 3.2.9 on 2022-10-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_alter_master_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='image',
            field=models.TextField(null=True),
        ),
    ]
