# Generated by Django 3.2.9 on 2022-10-28 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0007_alter_master_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='image',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
